//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenserAPIService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense_Category
    {
        public decimal ExpenseCategory { get; set; }
        public decimal ExpenseSubCategory { get; set; }
        public string ExpenseName { get; set; }
        public System.DateTime ChangeDateTime { get; set; }
        public string ChangeId { get; set; }
    }
}
