//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenserAPIService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Mobile
    {
        public string UserId { get; set; }
        public decimal Mobile { get; set; }
        public decimal CountryCode { get; set; }
        public string Prefix { get; set; }
        public System.DateTime ChangeDateTime { get; set; }
        public string ChangeId { get; set; }
    }
}
